In [5]:
import pandas as pd
import numpy as np
from datetime import datetime
import os
from simulation import Simulation
from glob import glob
from matplotlib import pyplot as plt
from matplotlib import ticker

In [6]:
data_files = sorted(glob('../../outputs/numpy_arrays/*'))

In [7]:
arr = np.load(data_files[1])

In [8]:
arr.shape

(51, 2, 2, 6)

In [9]:
arr_first_year = arr[0]
arr_first_year.shape

(2, 2, 6)

In [11]:
# percent non-hispanic black
# and percent all other
# we see 87.8 % nonblack

np.sum(arr_first_year, axis=(1,2)) / np.sum(arr_first_year)

array([0.87778426, 0.12221574])

In [12]:
# percent smoking states in wave 3

np.sum(arr_first_year, axis=(0,1)) / np.sum(arr_first_year)

array([0.60368669, 0.17545039, 0.07014472, 0.11675529, 0.0339629 ,
       0.        ])

In [13]:
# percent poverty

np.sum(arr_first_year, axis=(0,2)) / np.sum(arr_first_year)

array([0.26612213, 0.73387787])