In [2]:
"""Seeing how to sample from Dirichlet and what the results might look like."""

'Seeing how to sample from Dirichlet and what the results might look like.'

In [1]:
import numpy as np
from tabulate import tabulate

In [2]:
printtab = lambda x : print(tabulate(x, headers='firstrow'))

In [5]:
alpha = np.array([0.24, 0.44, 0.19, 0.14])*1000
s = np.random.dirichlet(alpha, 1)

ValueError: alpha <= 0

In [4]:
s

array([[0.23441026, 0.44673798, 0.18983018, 0.12902157]])

In [7]:
header = [
    "quit",
    "swtich to nonmenthol",
    "continue using menthol",
    "switch to ecig/dual",
]
tab = [header] + [[f"{np.around(100* e, 1)}%" for e in row] for row in s[:10]]

In [8]:
printtab(tab)

quit    swtich to nonmenthol    continue using menthol    switch to ecig/dual
------  ----------------------  ------------------------  ---------------------
24.4%   43.2%                   18.3%                     14.0%
22.2%   44.3%                   19.4%                     14.2%
21.7%   43.9%                   18.7%                     15.7%
25.1%   45.1%                   16.6%                     13.1%
25.1%   42.9%                   17.3%                     14.6%
25.0%   40.9%                   20.2%                     14.0%
21.7%   46.9%                   16.6%                     14.8%
24.0%   42.0%                   19.7%                     14.2%
24.1%   41.2%                   18.6%                     16.1%
21.5%   45.2%                   18.8%                     14.4%


In [11]:
print(np.mean(s, axis=0))
print(np.std(s, axis=0))

[0.23782486 0.43529047 0.18832808 0.13855659]
[0.01330031 0.01550693 0.01232497 0.0109193 ]


In [12]:
print(np.min(s, axis=0))
print(np.max(s, axis=0))

[0.18639193 0.37899825 0.14698373 0.10064999]
[0.28603816 0.50454302 0.24422038 0.18567981]


In [13]:
p = np.array([[0.24, 0.44, 0.19, 0.14]] * 10)

In [14]:
k = p + 0.1*(s[:10] - 0.25)

In [15]:

header = [
    "quit",
    "swtich to nonmenthol",
    "continue using menthol",
    "switch to ecig/dual",
]
tab = [header] + [[f"{np.around(100* e, 1)}%" for e in row] for row in k]
printtab(tab)

quit    swtich to nonmenthol    continue using menthol    switch to ecig/dual
------  ----------------------  ------------------------  ---------------------
23.9%   45.8%                   18.3%                     12.9%
23.7%   45.9%                   18.4%                     12.9%
23.7%   45.9%                   18.4%                     13.1%
24.0%   46.0%                   18.2%                     12.8%
24.0%   45.8%                   18.2%                     13.0%
24.0%   45.6%                   18.5%                     12.9%
23.7%   46.2%                   18.2%                     13.0%
23.9%   45.7%                   18.5%                     12.9%
23.9%   45.6%                   18.4%                     13.1%
23.7%   46.0%                   18.4%                     12.9%
