In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import os
from simulation import simulation

ImportError: cannot import name 'simulation' from 'simulation' (/home/nick/Gillings_work/menthol-model/menthol-model/simulation.py)

In [ ]:
now = datetime.now()
print("current time: " + now.strftime("%Y-%m-%d_%H-%M-%S-%f"))

current time: 2021-11-12_09-34-46-194898


In [ ]:
pop_file_name = "../../data/age_individual_October21_renamed.xlsx"
pop_df = pd.read_excel(pop_file_name)

In [ ]:
print(pop_df.columns)
print(pop_df.to_numpy()[0])

Index(['agegrp', 'sex', 'black', 'state_2', 'state_3', 'initiation_age_grp',
       'poverty', 'set', 'weight', 'age', 'start_age', 'isalive'],
      dtype='object')
[0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
 1.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
 6.98286028e+03 1.80000000e+01 0.00000000e+00 1.00000000e+00]


In [ ]:
pop_arr = pop_df.to_numpy()
print(pop_arr.shape)

(19212, 12)


In [ ]:
sum((np.count_nonzero(pop_arr[:,3] == 1),
np.count_nonzero(pop_arr[:,3] == 2),
np.count_nonzero(pop_arr[:,3] == 3),
np.count_nonzero(pop_arr[:,3] == 4),
np.count_nonzero(pop_arr[:,3] == 5)))

19212

In [ ]:
beta234_f = "../../beta_estimates/beta_estimates_234.xlsx"
beta15_f = "../../beta_estimates/beta_estimates_15.xlsx"
beta234 = pd.read_excel(beta234_f)
beta234.to_numpy()[:,2:]

array([[-1.5686870228174998, 1.0051432761259584, 1.9210998718763235,
        0.764676044288975, -0.48754878414369784, 2.611010345069931,
        0.39543336726452877, -0.937875179639555, -0.343479775900196,
        -0.26186218879129924, 0.44132656634025086, 0.0024031182569650904,
        0.030713617110619495, 0.4126644658141625],
       [0.7307493211073212, 0.14608387151766564, -0.31251275044869997,
        1.2787145998620204, -1.134829534153886, -0.06818658956922447,
        1.792267104303754, -2.0800940399141035, -0.5498745475178917,
        -0.7439717280682979, 0.9641128755653908, -0.009618339439985189,
        0.0913697963098372, -0.09960892427809044],
       [2.9132608274697724, -1.2046883293926811, -1.5277858505358368,
        -0.9260452395730414, -2.006549009181033, -2.541414388454822,
        -1.8625582113814683, -3.7059472023294866, 0.48246662321167916,
        0.39725840909952864, 0.05342761924435626, -0.02609917433217575,
        0.08608809207615274, 0.012450295752821961]], d

In [ ]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.delete(a, [0,1,2,3,4], axis=0)

array([], shape=(0, 5), dtype=int64)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.asarray([True, False], dtype=np.float32)

array([1., 0.], dtype=float32)

In [ ]:
b = np.arange(10).reshape((1,-1))
c = np.concatenate([None, b], axis=0)
c

ValueError: zero-dimensional arrays cannot be concatenated

In [2]:
a = np.asarray([[]])
a.shape

(1, 0)

In [ ]:
a = [1,2,3,]

In [ ]:
os.getcwd()


'/home/nick/Gillings_work/menthol-model/menthol-model'

In [ ]:
df = pd.read_excel("../../life_tables/2016/Males/life_table_2016_male.xlsx").to_numpy()
df[2:-1,1].shape

(101,)

In [ ]:
# 0 is male, 1 is female
life_table_dict = {}
life_table_dict[2016] = {}
life_table_dict[2017] = {}
life_table_dict[2018] = {}
life_table_dict[2016][0] = pd.read_excel("../../life_tables/2016/Males/life_table_2016_male.xlsx").to_numpy()[2:-1,1]
life_table_dict[2017][0] = pd.read_excel("../../life_tables/2017/Male/life_table_2017_male.xlsx").to_numpy()[2:-1,1]
life_table_dict[2018][0] = pd.read_excel("../../life_tables/2018/Males/life_table_2018_male.xlsx").to_numpy()[2:-1,1]
life_table_dict[2016][1] = pd.read_excel("../../life_tables/2016/Females/life_table_2016_female.xlsx").to_numpy()[2:-1,1]
life_table_dict[2017][1] = pd.read_excel("../../life_tables/2017/Female/life_table_2017_female.xlsx").to_numpy()[2:-1,1]
life_table_dict[2018][1] = pd.read_excel("../../life_tables/2018/Females/life_table_2018_female.xlsx").to_numpy()[2:-1,1]



In [ ]:
np.random.rand(10)

array([0.50643953, 0.64423564, 0.96482757, 0.5102111 , 0.05514091,
       0.41427298, 0.32974077, 0.84700337, 0.47347319, 0.43553276])

In [ ]:
a = np.arange(11)
b = [i % 11 for i in range(50)]
a[b][a[b] < np.arange(50)].shape

(39,)

In [ ]:
a is None

False

In [ ]:
a is not None

True

In [ ]:
None is None

True

In [ ]:
True and True

True

In [ ]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
a[a % 2 == 0] = 50

In [ ]:
a[:,1:3]

array([[ 1, 50],
       [50,  7],
       [11, 50],
       [50, 17],
       [21, 50]])

In [ ]:
a[:,4:]

array([[50],
       [ 9],
       [50],
       [19],
       [50]])

In [ ]:
a[:,:-1]

array([[50,  1, 50,  3],
       [ 5, 50,  7, 50],
       [50, 11, 50, 13],
       [15, 50, 17, 50],
       [50, 21, 50, 23]])

In [ ]:
[i for i in range(1,5)]

[1, 2, 3, 4]

In [ ]:
True == 1

True

In [ ]:
probs1 = np.random.rand(10)
probs2 = np.random.rand(10)

probs = [probs1, probs2, 2 - probs1 - probs2]

probs = np.asarray(probs).transpose() / 2

probs

array([[0.40025056, 0.0051937 , 0.59455574],
       [0.44018341, 0.17977848, 0.38003811],
       [0.38248601, 0.09057665, 0.52693734],
       [0.32022632, 0.31577831, 0.36399537],
       [0.01914356, 0.05421266, 0.92664378],
       [0.13897736, 0.40213485, 0.45888779],
       [0.25641793, 0.087665  , 0.65591708],
       [0.42384571, 0.18741424, 0.38874005],
       [0.19186251, 0.37914637, 0.42899112],
       [0.29507608, 0.22057022, 0.48435369]])

In [ ]:
chance = np.random.rand(probs.shape[0])[:,np.newaxis]
chance

array([[0.20637966],
       [0.27418093],
       [0.31499787],
       [0.63475707],
       [0.11835867],
       [0.25386809],
       [0.74509263],
       [0.72833473],
       [0.03579016],
       [0.06133095]])

In [ ]:
forward234 = np.concatenate([chance < np.sum(probs[:,:i], axis=1)[:,np.newaxis] for i in range(1, probs.shape[1] + 1)], axis=1)
backward234 = np.concatenate([(1-chance) < np.sum(probs[:,i:], axis=1)[:,np.newaxis] for i in range(probs.shape[1])], axis=1)

new_states234_uncut = forward234 * backward234 # need to do a AND

forward234, backward234

(array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [False,  True,  True],
        [False, False,  True],
        [False,  True,  True],
        [False, False,  True],
        [False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True, False, False],
        [ True, False, False],
        [ True, False, False],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True, False, False],
        [ True, False, False]]))

In [ ]:
forward234 * backward234

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False]])

In [ ]:
a = np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a[np.zeros(5).astype(np.bool_)].size

0

In [ ]:
a = np.array([300000001.])
a

array([3.00000001e+08])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.astype(np.float64)

array([3.00000001e+08])