In [1]:

from simulation import Simulation
import pandas as pd
import numpy as np
import argparse
import os
from datetime import datetime
from scipy.stats import truncnorm
import math

In [2]:
csvns_arr = pd.read_excel(os.path.join("..", "..", "smoking_mortality", "csvns_bounds.xlsx")).to_numpy()[:,1:]
fsvcs_arr = pd.read_excel(os.path.join("..", "..", "smoking_mortality", "fsvcs_bounds.xlsx")).to_numpy()[:,1:]

# create unit truncated normal to be used for confidence interval sampling
unit_truncnorm = truncnorm(-1.96, 1.96) # 1.96 is z score for 95% confidence interval

In [6]:

for row in csvns_arr:
    men_mean = row[0]
    women_mean = row[1]
    men_lower = row[2]
    women_lower = row[3]
    men_upper = row[4]
    women_upper = row[5]

    print("diffs")
    print(np.log(men_mean) - np.log(men_lower), np.log(men_upper) - np.log(men_mean))    
    print(np.log(women_mean) - np.log(women_lower), np.log(women_upper) - np.log(women_mean))    

    print("logvals")
    print(np.log([men_lower, men_mean, men_upper]))
    print(np.log([women_lower, women_mean, women_upper]))

    print("vals")
    print([men_lower, men_mean, men_upper])
    print([women_lower, women_mean, women_upper])

diffs
0.1769307081590783 0.17327172127403667
0.20479441264601317 0.13815033848081715
logvals
[1.13140211 1.30833282 1.48160454]
[0.78845736 0.99325177 1.13140211]
vals
[3.1, 3.7, 4.4]
[2.2, 2.7, 3.1]
diffs
0.09237332013101507 0.08455738802806323
0.10536051565782634 0.06453852113757108
logvals
[1.13140211 1.22377543 1.30833282]
[0.99325177 1.09861229 1.16315081]
vals
[3.1, 3.4, 3.7]
[2.7, 3.0, 3.2]
diffs
0.058840500022933506 0.055569851154810834
0.06669137449867235 0.06252035698133396
logvals
[1.19392247 1.25276297 1.30833282]
[1.06471074 1.13140211 1.19392247]
vals
[3.3, 3.5, 3.7]
[2.9, 3.1, 3.3]
diffs
0.06252035698133396 0.02985296314968111
0.06669137449867235 0.03174869831458027
logvals
[1.13140211 1.19392247 1.22377543]
[1.06471074 1.13140211 1.16315081]
vals
[3.1, 3.3, 3.4]
[2.9, 3.1, 3.2]
diffs
0.03922071315328124 0.07410797215372178
0.07696104113612834 0.03636764417087468
logvals
[0.91629073 0.95551145 1.02961942]
[0.91629073 0.99325177 1.02961942]
vals
[2.5, 2.6, 2.8]
[2.5, 2.7,